AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM template to create a free tier EC2 instance

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0453ec754f44f9a4a  # Replace with a valid AMI ID- Free tier
      KeyName: mosh-iam-admin-keypair   # Replace with an actual key pair name
      InstanceType: t2.micro
      SecurityGroupIds:
        - sg-020c305a248af1859
      SubnetId: subnet-08b3656203e9dfa33
      Tags:
        - Key: Name
          Value: Mosh-EC2
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          service httpd start
          chkconfig httpd on