version = 0.1
[default.deploy.parameters]
stack_name = "mmr-app-hosting-with-cicd-s3"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
resolve_s3 = true
s3_prefix = "mmr-app-hosting-with-cicd-s3"
